#!/usr/bin/env python3
"""Reject distribution archives containing interpreter-generated bytecode."""

from __future__ import annotations

import argparse
import sys
import tarfile
import zipfile
from pathlib import Path


def _is_bytecode(path: str) -> bool:
    normalized = path.replace("\\", "/")
    return "/__pycache__/" in f"/{normalized}" or normalized.endswith((".pyc", ".pyo"))


def archive_members(archive: Path) -> list[str]:
    if archive.suffix == ".whl":
        with zipfile.ZipFile(archive) as handle:
            return handle.namelist()
    if archive.name.endswith((".tar.gz", ".tgz", ".tar")):
        with tarfile.open(archive) as handle:
            return handle.getnames()
    raise ValueError(f"unsupported archive format: {archive}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archives", nargs="+", type=Path)
    args = parser.parse_args(argv)

    failures: list[str] = []
    for archive in args.archives:
        try:
            members = archive_members(archive)
        except (OSError, tarfile.TarError, zipfile.BadZipFile, ValueError) as exc:
            parser.error(str(exc))
        offenders = [member for member in members if _is_bytecode(member)]
        if offenders:
            failures.extend(f"{archive}: {member}" for member in offenders)
    if failures:
        print("Generated bytecode found in distribution archive:", file=sys.stderr)
        print("\n".join(failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
